development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:c0ce5f93cf72bd1c5df7e1baa8472d05@hammerjaw.redistogo.com:9901/
  channel_prefix: instatalk_production
